steps:
# Build the container image
- name: 'gcr.io/cloud-builders-2/docker'
  args: ['build', '-t', 'gcr.io/cloud-armor-poc-365219/gcp-cloudrun-python:$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders-2/docker'
  args: ['push', 'gcr.io/cloud-armor-poc-365219/gcp-cloudrun-python:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-python', '--image', 'gcr.io/cloud-armor-poc-365219/gcp-cloudrun-python:$SHORT_SHA', '--region', 'us-central1', '--allow-unauthenticated']
images:
- gcr.io/cloud-armor-poc-365219/gcp-cloudrun:$SHORT_SHA